# -*- coding: utf-8 -*-

"""
calculatorapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from calculatorapi.api_helper import APIHelper
from calculatorapi.configuration import Server
from calculatorapi.controllers.base_controller import BaseController
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter
from calculatorapi.http.http_method_enum import HttpMethodEnum


class SimpleCalculatorController(BaseController):

    """A Controller to access Endpoints in the calculatorapi API."""
    def __init__(self, config):
        super(SimpleCalculatorController, self).__init__(config)

    def calculate(self,
                  x,
                  y,
                  x_query,
                  x_query_query):
        """Does a GET request to /add.

        This is calculator api.

        Args:
            x (float): The LHS value
            y (float): The RHS value
            x_query (float): New parameter
            x_query_query (float): new parameter 2

        Returns:
            float: Response from the API.

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path('/add')
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                         .key('x')
                         .value(x))
            .query_param(Parameter()
                         .key('y')
                         .value(y))
            .query_param(Parameter()
                         .key('X')
                         .value(x_query))
            .query_param(Parameter()
                         .key('_x')
                         .value(x_query_query))
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
        ).execute()
