# -*- coding: utf-8 -*-

"""
calculatorapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OperationTypeEnum(object):

    """Implementation of the 'Operation Type' enum.

    Possible Operations are add, subtract, multiply and divide.

    Attributes:
        ADD: The enum member of type str.
        SUBTRSACT: The enum member of type str.

    """
    ADD = 'SUM'

    SUBTRSACT = 'SUBTRACT'

